### PR TITLE
add Docker service with workspace indexing

### PR DESCRIPTION
**Pull request by bertsky**
This adds the [recipe](https://github.com/OCR-D/ocrd-website/wiki/browse-ocrd-in-Docker) by @b2m for running OCR-D Browser inside a Broadwayd via Docker into the repository. I took the liberty of extending that idea with a simplistic indexing service which just searches for all METS files in the startup directory recursively, and presents a web page with links to each of them. The links then in turn will start up `browse-ocrd` and redirect to the local Broadwayd site.

Here's a screenshot of the index page:
ocrd-browser-browser

And that's what you get by clicking on one of the links:
ocrd-browser-broadway

### CODE REVIEW

**Comment by bertsky** [comment]
Note: I also updated the README in anticipation of a merge. There – besides describing the Docker option – I also added a table of contents on top.

Note: the current version can already be pulled as `bertsky/ocrd_browser` from Dockerhub. If you intend to support this yourself, we should rewrite the README to point to `hnesk/ocrd_browser` or even `ocrd/browser`, and add a CI for building and uploading the image, too.

**Comment by hnesk** [comment]
Nice! I was able to get it running immediately. 
This would work on windows, too, right?

The CI idea is great, but  I have nearly no experience with docker. 
I don't like the idea of  an `hnesk/ocrd_browser` image on dockerhub, because it would have name on it, but I wouldn't be able to support it, so both `bertsky/ocrd_browser` or `ocrd/browser` would be fine with me. 
So I'm not quite sure how to move on. Maybe we should add the docker image building process to the [CI workflow of browse-ocrd](https://github.com/hnesk/browse-ocrd/blob/master/.github/workflows/) of this repository or we find another place in the [ocrd scope](https://github.com/OCR-D/). Or would it make sense to have the dockerization/broadwayization in a complete separate repository? 

I'm open for any solution (also simply merging this right away), I just want to discuss this under the condition that I won't be able provide a lot o support for that feature.

**Comment by bertsky** [comment]
> This would work on windows, too, right?

Yes. And on headless servers.

> The CI idea is great, but I have nearly no experience with docker.

Ok, I'll create a configuration on my fork's master with credentials for my Dockerhub login, so we can c&p here.

> I don't like the idea of an `hnesk/ocrd_browser` image on dockerhub, because it would have my name tag on it, but I wouldn't be able to support it

It's your app and repo, though. And you can just set `MAINTAINER https://github.com/hnesk/browse-ocrd/issues` in the image. If you still don't like the responsibility (and credit), we could ask @kba for a transferral to github.com/OCR-D ...

> so both `bertsky/ocrd_browser` or `ocrd/browser` would be fine with me.

For the former I'd have to add my DH credentials to your repo (which I have no problem with), in the latter @kba's (not so sure).

> I'm not quite sure how to move on. Maybe we should add the docker image building process to the [CI workflow of browse-ocrd](https://github.com/hnesk/browse-ocrd/blob/master/.github/workflows/) of this repository

Let's see how far I get with that and then discuss!

> Or would it make sense to have the dockerization/broadwayization process in a complete separate repository?

We already did that in our https://github.com/markusweigelt/ocrd_manager/pull/17, but I think it's worth sharing here, too.

**Comment by bertsky** [comment]
> Ok, I'll create a configuration on my fork's master with credentials for my Dockerhub login, so we can c&p here.

It's as simple as https://github.com/bertsky/browse-ocrd/commit/dcc7230185f0746fafb69b01fa5d2c19aac4b3b7 and adding secrets `DOCKERHUB_USERNAME` and `DOCKERHUB_TOKEN` in your project settings.

(Name/tag of the image will have to be adapted of course.)

**Comment by hnesk** [comment]
Ok, I'm fine to publish this as [`hnesk/ocrd_browser`](https://hub.docker.com/r/hnesk/ocrd_browser). 
I just tested it with my credentials and it worked quite well, now I'm try to make it dependent on the unittest workflow and then from my end this can be merged. Do you agree?

**Pull request merged**
